name: BookMiner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run BookMiner
        run: python bookminer.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: se-ed-books
          path: se_ed_books.csv
